vigir_footstep_planning_msgs/StepPlan step_plan
---
vigir_footstep_planning_msgs/FootstepExecutionStatus status
int8 controller_state                               # final state of walk controller
---
std_msgs/Header header

uint8 NOT_READY = 0
uint8 READY     = 1
uint8 ACTIVE    = 2
uint8 PAUSED    = 3
uint8 FINISHED  = 4
uint8 FAILED    = 5
int8 controller_state                               # current state of walk controller

vigir_footstep_planning_msgs/ErrorStatus status     # error status of walk controller

int32 queue_size                                    # number of steps enqueued
int32 first_queued_step_index                       # first step index in queue
int32 last_queued_step_index                        # last step index in queue

int32 last_performed_step_index                     # latest step which execution was already performed and finished
int32 currently_executing_step_index                # current step which is executed
int32 first_changeable_step_index                   # first step which may be changed

int32 stepping_status                               # Use FootstepExecutionStatus.msg values

vigir_footstep_planning_msgs/StepPlanFeedback feedback
