vigir_footstep_planning_msgs/Feet feet
std_msgs/String target_frame            # should be "planner" or "robot"
---
vigir_footstep_planning_msgs/Feet feet
vigir_footstep_planning_msgs/ErrorStatus status
